### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by erwingaitano** [NerdWallet/nw-react-slider#1]
Running `npm install --save nw-react-slider` throws an error:

```
npm ERR! fetch failed https://registry.npmjs.org/nw-react-slider/-/nw-react-slider-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/nw-react-slider/-/nw-react-slider-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by dtschust** [comment]
Hi @erwingaitano, apologies but I just saw this issue. This was related to an issue on npm's end, reported [here](http://status.npmjs.org/incidents/7n06gj3f83tz). I've published an identical v1.0.1 which should fix the issue, please let me know if you have any further problems!
