### ISSUE TITLE
Value not updating correctly when being moved along slider.

### ISSUE THREAD

**Issue by clothiersphere** [NerdWallet/nw-react-slider#18]
Hi,

The value doesn't change when sliding the toggle on the bar like in example. What am I doing wrong?

<img width="351" alt="screen shot 2016-10-10 at 5 00 10 pm" src="https://cloud.githubusercontent.com/assets/7027517/19254715/94336a50-8f0b-11e6-9326-e3acf388fb05.png">

**Comment by clothiersphere** [comment]
<img width="351" alt="screen shot 2016-10-10 at 5 00 10 pm" src="https://cloud.githubusercontent.com/assets/7027517/19254710/87ee9602-8f0b-11e6-9154-aa6753d0481a.png">

**Comment by akshat1** [comment]
Hi @clothiersphere! Do you see any errors in the terminal or the browser console?

**Comment by clothiersphere** [comment]
None. Everything works fine except the value is not updating. When I select
a new value on the slider I'm able to console log and pass that value
correctly, but when I click the slider again - the slider resets to 0.
Conversely the displayFollowerPopover always shows as 0 - despite me being
able to log the value being selected.

I will try to do more testing or something fresh instead of incorporating
something since I'm sure it's something on my end.

**Comment by clothiersphere** [comment]
So I completely took everything out except for the slider.

Here the min is 0 the max is 5 and the value is 0.

First thing I do is click the the 2nd tick and correctly pass the value of
the selected bar to my action creator ( note payload is passing back 2 )
(also note that the slider toggle/icon is still at 0.

Then I select the 4th tick and the value being passed is 4. ( popup still
shows 0 ).

Now I select the 3rd tick and the value passed is 3, but the slider dot
resets back to the 0 position.


[image: Inline image 1][image: Inline image 2][image: Inline image 3]

**Comment by akshat1** [comment]
I'm sorry but I can't seem to reproduce your issue with the demo page. Also, can't see your screenshots.

If you are using this in a public repo then perhaps I could take a look at the source?
